{% set name = "requests-async" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8731420451383196ecf2fd96082bfc8ae5103ada90aba185888499d7784dde6f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - httpcore ==0.3.*
    - python >=3.6
    - requests ==2.*

test:
  imports:
    - requests_async

about:
  home: https://github.com/encode/requests-async
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE.md
  summary: async-await support for `requests`.

extra:
  recipe-maintainers:
    - nicoddemus
