travis:
  secure:
    BINSTAR_TOKEN: J2LI2XTWiR6kK/MGZXGaMpqs7P2ZgHV/N+a9nJMayjmpr/OCtnu+CpD6XrPVuRIpLvB3pPTkTGaOADUpk1JxN3+2T1ki+ScNaQqfsPYHivcHKVlWFaE3ZT5WpQb5K1QEEvgwNc1jzsAce0ahu92Kc1GXMQYQj2iG/XXaBgizsp6KyAJZnBLQMKp9L85oUY+shbsmnhFltyHXG1iO25owmwa/yU8HvEyGBMWXhgjQZATjgQBMhTKBMNWSdWTMwsqcuTBliPkcgROQ5yEMxU7u6urM+3RVG8ptWI6yqRLVFmIndf6GAjVolS+tVMuOXEhv08S4EeFsRi5PTVeJvbp28ny5tPjbPq41suXoXSq1FS6pMBw5Rz77J4Cd5Vi7nDl1uWcjNaIYPfVOh9nsqh502oP8O4evqu+Fq7wLsilwNSXRgIjHtwwTo6TcQYCQDzY6VEkbrSDrORWqkExyvZ6WfIi5sa8fUm3kiQBnlQnFE/SrS7mVRqehVJLv6cmuMg/d/GIwfwn5jqzbcZyCdT4jVqDCVatmHk6/2ViLCSdDul+bX+doZWoJOEdEeNwri3JDj7ETh/tO92aa8fSgOm45cV42L6YkuXeJLq/rLGbDJAyKUt350xVY7NzIA7JYm//YA8WcqjlZ5TAhxx0N7yIkJZ6R8XcfF/J2nir3jtBTfJc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
